import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Don't say 10</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Don't Say 10</h1>
        <p></p>

        <div className={styles.grid}>
          <a className={styles.card}>
            <h2 style={{ textAlign: "center" }}>+1</h2>
            <p>Adds 1 for your turn</p>
          </a>

          <a className={styles.card}>
            <h2 style={{ textAlign: "center" }}>+2</h2>
            <p>Adds 2 for your turn</p>
          </a>
          <a className={styles.card}>
            <h2 style={{ textAlign: "center" }}>+3</h2>
            <p>Adds 3 for your turn</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://andrewli.site"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made by Andrew
        </a>
      </footer>
    </div>
  );
}
